#!/usr/bin/env bash

git config --global user.name 'github-actions'
git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

scripts/slacktenure 'Tenures at company'
status=$(git status --porcelain)
if [[ -n $status ]]; then
	git add diffs
	git commit --all --message="Update tenures"
	git push

	diffs=(diffs/*.diff)
	diff=${diffs[-1]}

	ref=$GITHUB_REF
	ref=${ref##*/}
	baseurl="https://github.com/$GITHUB_REPOSITORY/blob/$ref"
	links="[Diff]($baseurl/$diff)"
	links+=" • [All tenures]($baseurl/outputs/tenures.md)"
	links+=" • [Current tenures]($baseurl/outputs/tenurescurrent.md)"
	printf -v msg '%s\n' "$links" '' '```diff' "$(< "$diff")" '```'
	escapedmsg=$(jq --raw-input --slurp '.' <<< "$msg")

	echo "::set-output name=msg::$escapedmsg"
fi

scripts/generateturnover data/tenures.tsv > data/turnover.tsv
status=$(git status --porcelain)
if [[ -n $status ]]; then
	sudo apt-get install gnuplot-nox
	gnuplot -c scripts/turnover.gpi svg
	gnuplot -c scripts/turnover.gpi png

	git commit --message="Update graph" -- data/turnover.tsv outputs/turnover.svg
	git push

	echo "::set-output name=sendmsg::true"
fi
