#!/usr/bin/env bash

awk -v now="$EPOCHSECONDS" '
	BEGIN { OFS = FS = "\t" }
	NR == 1 { next }
	$5 {
		$6 = $6 ? $6 : now
		print $1, $2, $6 - $5
	}
' tenures.tsv \
	| while IFS=$'\t' read -r _ name secs; do
		printf '%s\t%d\n' "$name" "$((secs / 24 / 3600))"
	done \
	| sort -n -t $'\t' -k2,2 \
	| column -t -s$'\t'
