#!/usr/bin/env bash

# Fetch complete users list from Slack API
getusers() {
	curl https://slack.com/api/users.list \
		--silent \
		--get \
		--data 'pretty=1' \
		--header "Authorization: Bearer $BOT_TOKEN"
}

# Remove bot and guest users
extractfullusers() {
	jq '
		.members |
		map(select(
			(
				.is_bot or .is_restricted |
				not
			)
			and .name != "slackbot"
		))
	'
}

# Fetch all users and extract full users
getfullusers() {
	getusers | extractfullusers
}

# Retrieve first or last message for user from Slack API; throw away response
# and retry once when hitting rate limit
findmsg() {
	local userid=$1
	local dir=$2

	curl https://slack.com/api/search.messages \
		--silent \
		--get \
		--data 'pretty=1' \
		--data-urlencode "query=from:<@$userid>" \
		--data 'count=1' \
		--data 'sort=timestamp' \
		--data "sort_dir=$dir" \
		--header "Authorization: Bearer $USER_TOKEN" \
		--retry 1 \
		| jq '
			if (.ok | not) and .error == "ratelimited" then
				empty
			else
				.
			end
		'
}

# Find first message from user
findfirst() {
	local userid=$1

	echo "Getting first message for $userid..." >&2
	findmsg "$userid" 'asc'
}

# Find last message from user
findlast() {
	local userid=$1

	echo "Getting last message for $userid..." >&2
	findmsg "$userid" 'desc'
}

# Extract timestamp from message search result; return non-zero exit status if
# user has no messages at all
msg2timestamp() {
	jq --raw-output '
		if .messages.total == 0 then
			"" | halt_error(1)
		else
			.messages.matches[0].ts |
			if test("[.]") then
				split(".")[0]
			else
				.
			end
		end
	'
}

# Convert user JSON to TSV input required for first/last lookup
extractids() {
	jq --raw-output '
		map([.id, .profile.real_name, .deleted, .profile.title]) |
		.[] |
		@tsv
	'
}

# Print user status and timestamps of the first and last ever message of the
# provided user; a user can have a status and zero, one, or two timestamps; if
# the user does not exist in infile (usually tenures.tsv), nothing is printed
gettenure() {
	local id=$1
	local infile=$2
	awk --field-separator '\t' --assign id="$id" '
		$1 == id {
			printf $4
			if ($5) {
				printf " " $5
				if ($6) {
					printf " " $6
				}
				print ""
			}
	}' "$infile"
}

# Check corrfile to see if it contains corrected values for the user identified
# by id; if so, print a comma-separated line with values indicating if the user
# should be deleted ("true" or empty), an optional corrected first seen
# timestamp, and an optional corrected last seen timestamp
getcorrections() {
	local corrfile=$1
	local id=$2

	[[ -r $corrfile ]] || return

	awk --field-separator ',' --assign id="$id" '
		BEGIN { OFS = "," }
		$1 == id { print $2, $3, $4 }
	' "$corrfile"
}

# For each user in infile, determine if newer information than available in
# datafile might exist and fetch it to update the record; use corrfile to
# override with manually corrected values
tenureupdate() {
	local infile=$1
	local datafile=$2
	local corrfile=$3

	printf '%s\t%s\t%s\t%s\t%s\t%s\n' 'id' 'name' 'title' 'status' 'first' 'last'

	local id name deleted title
	while IFS=$'\t' read -r id name deleted title; do
		# Get corrected data
		local delete corrfirst corrlast
		IFS=, read -r delete corrfirst corrlast <<< "$(getcorrections "$corrfile" "$id")"
		if [[ $delete == 'true' ]]; then
			# Skip deleted entry
			unset id name deleted title delete corrfirst corrlast
			continue
		fi

		local oldstatus first last
		read -r oldstatus first last <<< "$(gettenure "$id" "$datafile")"
		local status=${oldstatus:=fresh}

		case $oldstatus in
			'active')
				if [[ $deleted == 'true' ]]; then
					# Newly alum, get last
					status='alum'
					last=$(findlast "$id" | msg2timestamp)
				fi
				;;

			'fresh')
				if first=$(findfirst "$id" | msg2timestamp); then
					status='active'
				fi

				if [[ $deleted == 'true' ]]; then
					if [[ $status == 'active' ]]; then
						status='alum'
						last=$(findlast "$id" | msg2timestamp)
					else
						status='noshow'
					fi
				fi
				;;
		esac

		# Use corrections where available
		first=${corrfirst:-$first}
		last=${corrlast:-$last}

		printf '%s\t%s\t%s\t%s\t%s\t%s\n' \
			"$id" "$name" "$title" "$status" "$first" "$last"
		unset id name deleted title first last status delete corrfirst corrlast
	done < <(extractids < "$infile")
}

# Filter for tenures.tsv to remove headers, drop status field, sort by join
# date, convert Unix timestamp to YYYY-MM-DD, and add employee number
prettyprint() {
	sed '1d' \
		| cut --fields=4 --complement \
		| sort --numeric-sort --key=4,4 --field-separator=$'\t' \
		| awk --field-separator='\t' --assign OFS='\t' '
			$4 {
				$4 = strftime("%F", $4)
				if ($5)
					$5 = strftime("%F", $5)
				print
			}
		' \
		| nl
}

# Filter for tenures.tsv to remove headers, sort by join date, filter for
# active users, convert Unix timestamp to YYYY-MM-DD, and add current employee
# number
prettyprintcurrent() {
	sed '1d' \
		| sort --numeric-sort --key=5,5 --field-separator=$'\t' \
		| awk --field-separator='\t' --assign OFS='\t' '
			$4 == "active" {
				print $1, $2, $3, strftime("%F", $5)
			}
		' \
		| nl
}

# Filter for prettyprint output to terminal
tocolumn() {
	column --table --separator=$'\t' --table-truncate=4
}

# Filter to convert tab separated input to body of Markdown table
mdtablebody() {
	sed --regexp-extended '
		s/^ +//     # Remove leading blanks
		s/\|/\\|/g  # Escape existing pipes
		s/\t/ | /g  # Replace tabs with pipes
		s/ +$//     # Remove trailing blanks
	'
}

# Filter for prettyprint output to Markdown
tomarkdown() {
	local title=$1
	printf '%s\n\n' "# $title"
	printf '%s | %s | %s | %s | %s | %s\n' \
		'\#' "User ID" "Name" "Title" "Joined" "Left" \
		'-:' '-' '-' '-' '-' '-'

	mdtablebody

}

# Filter for prettyprintcurrent output to Markdown
tomarkdowncurrent() {
	local title=$1
	printf '%s\n\n' "# $title"
	printf '%s | %s | %s | %s | %s\n' '\#' "User ID" "Name" "Title" "Joined" \
		'-:' '-' '-' '-' '-'

	mdtablebody
}

# Make sure required environment variables are defined
checkenvvars() {
	local envvar
	for envvar in BOT_TOKEN USER_TOKEN; do
		if [[ -z ${!envvar} ]]; then
			echo "$envvar must be set" >&2
			return 1
		fi
	done

	return 0
}

# Update link to diff file in README
updatedifflink() {
	local difffile=$1
	sed --regexp-extended --in-place \
		"s|(\[latest diff\])\((.*)\)|\1($difffile)|" README.md
}

main() {
	checkenvvars || exit 1

	local title=${1:-Tenures}

	# Update data
	getfullusers > users.json
	[[ -e data/tenures.tsv ]] || touch data/tenures.tsv
	tenureupdate users.json data/tenures.tsv data/corrections.csv > data/tenures_new.tsv
	rm users.json

	# Prepare diff
	local difffile
	difffile="diffs/update-$(date '+%F-%H').diff"
	diff --unified data/tenures.tsv data/tenures_new.tsv | tee "$difffile"
	mv data/tenures_new.tsv data/tenures.tsv

	if ! [[ -s $difffile ]]; then
		echo "Nothing changed!" >&2
		rm "$difffile"
		exit
	fi

	updatedifflink "$difffile"

	# Update Markdown tables
	prettyprint < data/tenures.tsv | tomarkdown "$title" > outputs/tenures.md
	prettyprintcurrent < data/tenures.tsv \
		| tomarkdowncurrent "$title, current" > outputs/tenurescurrent.md
}

[[ ${BASH_SOURCE[0]} == "$0" ]] && main "$@"
