#!/usr/bin/env bash

# Fetch complete users list from Slack API
getusers() {
	curl https://slack.com/api/users.list \
		--silent \
		--get \
		--data 'pretty=1' \
		--header "Authorization: Bearer $BOT_TOKEN"
}

# Remove bot and guest users
extractfullusers() {
	jq '
		.members |
		map(select(
			(
				.is_bot or .is_restricted |
				not
			)
			and .name != "slackbot"
		))
	'
}

# Fetch all users and extract full users
getfullusers() {
	getusers | extractfullusers
}

# Retrieve first or last message for user from Slack API; throw away response
# and retry once when hitting rate limit
findmsg() {
	local userid=$1
	local dir=$2

	curl https://slack.com/api/search.messages \
		--silent \
		--get \
		--data 'pretty=1' \
		--data-urlencode "query=from:<@$userid>" \
		--data 'count=1' \
		--data 'sort=timestamp' \
		--data "sort_dir=$dir" \
		--header "Authorization: Bearer $USER_TOKEN" \
		--retry 1 \
		| jq '
			if (.ok | not) and .error == "ratelimited" then
				empty
			else
				.
			end
		'
}

# Find first message from user
findfirst() {
	local userid=$1

	echo "Getting first message for $userid..." >&2
	findmsg "$userid" 'asc'
}

# Find last message from user
findlast() {
	local userid=$1

	echo "Getting last message for $userid..." >&2
	findmsg "$userid" 'desc'
}

# Extract timestamp from message search result; return non-zero exit status if
# user has no messages at all
msg2timestamp() {
	jq --raw-output '
		if .messages.total == 0 then
			"" | halt_error(1)
		else
			.messages.matches[0].ts |
			if test("[.]") then
				split(".")[0]
			else
				.
			end
		end
	'
}

# Convert user JSON to TSV input required for first/last lookup
extractids() {
	jq --raw-output '
		map([.id, .profile.real_name, .deleted, .profile.title]) |
		.[] |
		@tsv
	'
}

# Print user status and timestamps of the first and last ever message of the
# provided user; a user can have a status and zero, one, or two timestamps; if
# the user does not exist in infile (usually tenures.tsv), nothing is printed
gettenure() {
	local id=$1
	local infile=$2
	awk --assign id="$id" '
		BEGIN { FS = "\t" }
		$1 == id {
			printf $4
			if ($5) {
				printf " " $5
				if ($6) {
					printf " " $6
				}
				print ""
			}
	}' "$infile"
}

# Check corrfile to see if it contains corrected values for the user identified
# by id; if so, print a comma-separated line with values indicating if the user
# should be deleted ("true" or empty), an optional corrected first seen
# timestamp, and an optional corrected last seen timestamp
getcorrections() {
	local corrfile=$1
	local id=$2

	[[ -r $corrfile ]] || return

	awk --assign id="$id" '
		BEGIN { FS = OFS = "," }
		$1 == id { print $2, $3, $4 }
	' "$corrfile"
}

# For each user in infile, determine if newer information than available in
# datafile might exist and fetch it to update the record; use corrfile to
# override with manually corrected values
tenureupdate() {
	local infile=$1
	local datafile=$2
	local corrfile=$3

	printf '%s\t%s\t%s\t%s\t%s\t%s\n' 'id' 'name' 'title' 'status' 'first' 'last'

	local id name deleted title
	while IFS=$'\t' read -r id name deleted title; do
		# Get corrected data
		local delete corrfirst corrlast
		IFS=, read -r delete corrfirst corrlast <<< "$(getcorrections "$corrfile" "$id")"
		if [[ $delete == 'true' ]]; then
			# Skip deleted entry
			unset id name deleted title delete corrfirst corrlast
			continue
		fi

		local oldstatus first last
		read -r oldstatus first last <<< "$(gettenure "$id" "$datafile")"
		local status=${oldstatus:=fresh}

		case $oldstatus in
			'active')
				if [[ $deleted == 'true' ]]; then
					# Newly alum, get last
					status='alum'
					last=$(findlast "$id" | msg2timestamp)
				fi
				;;

			'fresh')
				if ! first=$(findfirst "$id" | msg2timestamp); then
					# Use "now" if no first message found
					printf -v first '%(%s)T' -2
				fi
				status='active'

				if [[ $deleted == 'true' ]]; then
					if ! last=$(findlast "$id" | msg2timestamp); then
						# Use "now" if no last message found
						printf -v last '%(%s)T' -2
					fi
					status='alum'
				fi
				;;
		esac

		# Use corrections where available
		first=${corrfirst:-$first}
		last=${corrlast:-$last}

		printf '%s\t%s\t%s\t%s\t%s\t%s\n' \
			"$id" "$name" "$title" "$status" "$first" "$last"
		unset id name deleted title first last status delete corrfirst corrlast
	done < <(extractids < "$infile")
}

# Filter for tenures.tsv to remove headers, drop status field, sort by join
# date, drop future start dates, convert Unix timestamp to YYYY-MM-DD, and add
# employee number
prettyprint() {
	sed '1d' \
		| cut --fields=4 --complement \
		| sort --numeric-sort --key=4,4 --field-separator=$'\t' \
		| awk '
			BEGIN {
				FS = OFS = "\t"
				now = systime()
			}
			$4 && $4 < now {
				$4 = strftime("%F", $4)
				if ($5)
					$5 = strftime("%F", $5)
				print
			}
		' \
		| nl
}

# Filter for tenures.tsv to remove headers, sort by join date, filter for
# active users, drop future start dates, convert Unix timestamp to YYYY-MM-DD,
# and add current employee number
prettyprintcurrent() {
	sed '1d' \
		| sort --numeric-sort --key=5,5 --field-separator=$'\t' \
		| awk '
			BEGIN {
				FS = OFS = "\t"
				now = systime()
			}
			$4 == "active" && $5 < now {
				print $1, $2, $3, strftime("%F", $5)
			}
		' \
		| nl
}

# Filter for tenures.tsv to remove headers, add indicator for active (current,
# "C") and alum (former, "F") users, drop future start dates and print length
# of tenure in days, then sort by longest tenure, descending, and add ranking
prettyprintduration() {
	awk '
		BEGIN {
			FS = OFS = "\t"
			now = systime()
		}
		NR == 1 { next }
		$5 && $5 < now {
			$6 = $6 ? $6 : now
			print ($6 == now ? "C" : "F"), $1, $2, $3, int(($6 - $5) / 24 / 3600)
		}
	' \
		| sort --numeric-sort --key=5,5 --field-separator=$'\t' --reverse \
		| nl --number-width=1
}

# Filter for prettyprint output to terminal
tocolumn() {
	column --table --separator=$'\t' --table-truncate=4
}

# Filter to convert tab separated input to body of Markdown table
mdtablebody() {
	sed --regexp-extended '
		s/^ +//     # Remove leading blanks
		s/\|/\\|/g  # Escape existing pipes
		s/\t/ | /g  # Replace tabs with pipes
		s/ +$//     # Remove trailing blanks
	'
}

# Filter for prettyprint output to Markdown
tomarkdown() {
	local name=$1
	printf '%s\n\n' "# Tenures at $name"
	printf '%s | %s | %s | %s | %s | %s\n' \
		'\#' "User ID" "Name" "Title" "Joined" "Left" \
		'--:' '---' '---' '---' '---' '---'

	mdtablebody

}

# Filter for prettyprintcurrent output to Markdown
tomarkdowncurrent() {
	local name=$1
	printf '%s\n\n' "# Tenures at $name, current"
	printf '%s | %s | %s | %s | %s\n' '\#' "User ID" "Name" "Title" "Joined" \
		'--:' '---' '---' '---' '---'

	mdtablebody
}

# Filter for prettyprintduration output to Markdown; sets lines for former
# employees in italics
tomarkdownduration() {
	local name=$1
	printf '%s\n\n' \
		"# Tenures at $name by duration" \
		"Lines in *italics* indicate former employees."
	printf '%s | %s | %s | %s | %s\n' '\#' "User ID" "Name" "Title" "Days" \
		'--:' '---' '---' '---' '--:'

	awk '
		BEGIN { FS = OFS = "\t" }
		$2 == "F" {
			for (i = 1; i <= NF; ++i) {
				if ($i && i != 2) {
					gsub(/^[[:blank:]]+|[[:blank:]]+$/, "", $i)
					$i = "*" $i "*"
				}
			}
		}
		{
			line = $1
			for (i = 3; i <= NF; ++i) {
				line = line OFS $i
			}
			print line
		}
	' \
		| mdtablebody
}

# Filter for stats output to Markdown
tomarkdownstats() {
	printf '%s | %s\n' 'What' 'Value [days]' \
		'---' '--:'

	mdtablebody
}

# Make sure required environment variables are defined
checkenvvars() {
	local envvar
	for envvar in BOT_TOKEN USER_TOKEN; do
		if [[ -z ${!envvar} ]]; then
			echo "$envvar must be set" >&2
			return 1
		fi
	done

	return 0
}

# Drop lines mentioning corrections if the file does not exist
dropcorrections() {
	if [[ ! -e data/corrections.csv ]]; then
		sed '\|data/corrections\.csv|d'
	else
		cat
	fi
}

# Update README file
updatereadme() {
	local name=$1
	local difffile=$2
	local statstable=$3
	local readme=$4

	cat <<- EOF | dropcorrections > "$readme"
		# Slack workspace analysis for $name

		**[All tenures][all] &ndash; [current employees][current] &ndash;
		[by duration][duration] &ndash; [latest diff][latest]**

		- Raw data is in [\`data/tenures.tsv\`][tenures]
		- Corrections are taken from [\`data/corrections.csv\`][corrections]

		## Employee turnover over time

		![Employee turnover over time][turnover]

		## Tenure statistics (all employees ever)

		$statstable

		Boxplot: box from 25th to 75th percentile with a line at the median;
		whiskers extend to the most distant point whose value lies within 1.5
		times the interquartile range, and outliers are plotted separately

		![Tenure boxplot][boxplot]

		<sub>Powered by [Slack analyzer][analyzer]</sub>

		[all]:         <tenures.md>
		[current]:     <tenurescurrent.md>
		[duration]:    <tenuresduration.md>
		[latest]:      <$difffile>
		[tenures]:     <data/tenures.tsv>
		[corrections]: <data/corrections.csv>
		[turnover]:    <turnover.svg>
		[boxplot]:     <boxplot.svg>
		[analyzer]:    <https://github.com/bewuethr/slack-analyzer>
	EOF
}

# Replace double quotes with single quotes so GitHub is not confused
fixquotes() {
	sed 'y/"/'\''/'
}

# Return path to new diff file and create directories if necessary
getdifffile() {
	local path
	printf -v path 'diffs/%(%Y/%m)T' -2
	mkdir --parents "$path"
	printf '%s/update-%(%F-%H%M)T.diff' "$path" -2
}

main() {
	checkenvvars || exit 1

	local name=$1

	# Update data
	getfullusers > users.json
	mkdir --parents data
	[[ -e data/tenures.tsv ]] || touch data/tenures.tsv
	tenureupdate users.json data/tenures.tsv data/corrections.csv \
		| fixquotes > data/tenures_new.tsv
	rm users.json

	# Prepare diff
	local difffile
	difffile=$(getdifffile)
	diff --unified=0 data/tenures.tsv data/tenures_new.tsv | tee "$difffile"
	mv data/tenures_new.tsv data/tenures.tsv

	if ! [[ -s $difffile ]]; then
		echo "Nothing changed!" >&2
		rm "$difffile"

		# Get most recent previous diff
		shopt -s globstar
		local diffs=(diffs/**/*.diff)
		difffile=${diffs[-1]}
	fi

	local curdir=${BASH_SOURCE[0]%/*}

	local statstable
	statstable=$(prettyprintduration < data/tenures.tsv \
		| cut --fields=6 \
		| "$curdir/stats" \
		| tomarkdownstats)

	updatereadme "$name" "$difffile" "$statstable" README.md

	# Update Markdown tables
	prettyprint < data/tenures.tsv \
		| tomarkdown "$name" > tenures.md

	prettyprintcurrent < data/tenures.tsv \
		| tomarkdowncurrent "$name" > tenurescurrent.md

	prettyprintduration < data/tenures.tsv \
		| tomarkdownduration "$name" > tenuresduration.md
}

if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
	main "$@"
fi
