#!/usr/bin/awk -f

NR == 1 { min = max = $1 }

{
	sum += $1
	arr[NR] = $1
	min = $1 < min ? $1 : min
	max = $1 > max ? $1 : max
}

END {
	printf "min\t%d\n", min
	printf "max\t%d\n", max

	printf "mean\t%d\n", sum / NR

	medianidx = int(NR / 2)
	if (! NR % 2) {
		median = arr[medianidx]
	}
	else {
		median = (arr[medianidx] + arr[medianidx+1]) / 2
	}
	printf "median\t%d\n", median
}
