name: Lint code base

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Lint code base
        uses: github/super-linter/slim@v4.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: |
            ${{ github.event_name == 'push' && github.ref_name == 'main' }}
